version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
    # expose the Minecraft server port outside of container
    - 25565:25565
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      VERSION: 1.12.2
      FORGEVERSION: 14.23.5.2854
      WORLD: /worlds/ic2
      ONLINE_MODE: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      VIEW_DISTANCE: 16
      OPS: "Stherlode,KlosTher,blerryzt"
      JVM_OPTS: "-Xmx7g -Xms5g"
    volumes:
    # use a named, managed volume for data volume
      - mc_forge:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
      - ./mods:/mods:ro
      - ./worlds:/worlds
      - ./server.properties:/server.properties

volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}